app/admin/models.py
from app import db

class Course(db.Model):
    __tablename__ = "login_courses"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String, nullable = False)
    title = db.Column(db.String, nullable = False)
    description = db.Column(db.Text, nullable = False)
    url = db.Column(db.String, unique = True, nullable = False)
    module = db.Column(db.Integer, nullable = False) 
    chapter = db.Column(db.Integer, nullable = False)
    category = db.Column(db.String, nullable = False)
    user_id = db.Column(db.Integer, db.ForeignKey('login_users.id'), nullable = False)

    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()

    def delete(self):
         db.session.delete(self)
         db.session.commit()

    @staticmethod
    def get_courses(id):
         return Course.query.filter_by(user_id = id).all()
    
    @staticmethod
    def get_by_id(id):
         return Course.query.get(id)
         

app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, TextAreaField
from wtforms.validators import DataRequired, Length

class CourseForm(FlaskForm):

    name = StringField(validators=[DataRequired(), Length(max=256)])
    title = StringField(validators=[DataRequired(), Length(max=256)])
    description = TextAreaField(validators=[DataRequired()])
    url = StringField(validators=[DataRequired()])
    module = IntegerField(validators=[DataRequired()])
    chapter = IntegerField(validators=[DataRequired()])
    category = StringField(validators=[DataRequired()])

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

# instancias
db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
login_manager = LoginManager()

def create_app(settings_module):
    app = Flask(__name__)
    app.config.from_object(settings_module) # captura el entorno en el que se va a trabajar
    db.init_app(app)
    migrate.init_app(app,db)
    bootstrap.init_app(app)
    login_manager.init_app(app)

    login_manager.login_view = "signin"

    from app.admin import admin
    from app.auth import auth

    app.register_blueprint(admin)
    app.register_blueprint(auth)

    with app.app_context():
        db.create_all()
        
    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates')

from . import routes

app/admin/routes.py
from flask import render_template, redirect, url_for, request
from flask_login import login_required, current_user
from .forms import CourseForm
from .models import Course

from app.auth.models import User, generate_password 

from . import admin


@admin.route('/dashboard/user/password/<int:id>', methods = ['GET', 'POST'])
@admin.route('/dashboard/user/password')
@login_required
def update_password(id:None):

    user = User.get_by_id(id)

    if request.method == "POST":
        new_password = request.form['password']
        user.username, user.email, user.password = user.username, user.email, generate_password(new_password)
        user.save()
        #return redirect(url_for('admin.dashboard_user'))
    return render_template('admin/update_password.html', title = "Update Password")


@admin.route('/dashboard/courses/add', methods=['GET', 'POST'])
@login_required
def add_courses():
    form = CourseForm(request.form)
    
    name, title, description = form.name.data, form.title.data, form.description.data
    url, module, chapter, category = form.url.data, form.module.data, form.chapter.data, form.category.data

    if form.validate_on_submit():

        course = Course(name = name, title = title, description = description, url = url, module = module,
                        chapter = chapter, category = category, user_id = current_user.id )
        
        course.save()

        return redirect(url_for('admin.get_courses'))
    return render_template('admin/course_form.html', title="Add Course", form = form)

@admin.route('/dashboard/courses/delete/<int:id>')
@login_required
def delete_course(id=None):

    course = Course.get_by_id(id)
    course.delete()
    return redirect(url_for('admin.get_courses'))

@admin.route('/dashboard/courses/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update_course(id=None):
    course = Course.get_by_id(id)
    form = CourseForm(obj=course)
    update_text = True
    if form.validate_on_submit():
        course.name, course.title, course.description = form.name.data, form.title.data, form.description.data     
        course.url, course.module, course.chapter, course.categoty = form.url.data, form.module.data, form.chapter.data, form.category.data 
        course.save()
        return redirect(url_for('admin.get_courses'))
    return render_template('admin/course_form.html', form = form, title = "Course Update", update = update_text)


@admin.route('/dashboard/courses')
@login_required
def get_courses():

    courses = Course.get_courses(int(current_user.id))
    
    return render_template('admin/courses.html', title = "Cursos", courses = courses)

app/templates/layout.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {{title}}
{% endblock %}

{% block styles %}
{{super()}}
<!-- En caso quiera importar alguno css -->
<!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" /> -->
{% endblock %}

<!--     <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <dic class="container">
            <a class="navbar-brand" href="#"></a>
            <div>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Index</a>
                    </li>
                </ul>
            </div>
        </dic>
    </nav> -->
{% block navbar %}    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        
            <a class="navbar-brand" href="/">Noa
                <img src="{{url_for('static', filename='img/aceite-de-palma.png')}}" alt="" width="30" height="30" class="d-inline-block align-top mr-1">
            </a>
            <div >
                {% if current_user.is_authenticated %}
                <ul class="nav justify-content-center">
                    <li>
                        <a href="{{url_for('admin.get_courses')}}" class="nav-link" style="color:aliceblue;">
                            <img src="{{url_for('static', filename='img/online-course.png')}}" alt="" width="25">
                            Cursos
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('admin.add_courses')}}" class="nav-link" style="color: aliceblue;">
                            <img src="{{url_for('static', filename='img/add.png')}}" alt="" width="25">
                            Agregar
                        </a>
                    </li>
                </ul>
                {% endif %}
            </div>
            <div>
                <ul class="nav justify-content-end">
                    
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.dashboard_user')}}" style="color: aliceblue;"> 
                            <img src="{{url_for('static', filename='img/hombre.png')}}" alt="figura de hombre" width="25"> 
                            {{current_user.username}}                            
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.logout')}}" style="color: aliceblue;">
                            <img src="{{url_for('static', filename='img/cerrar-sesion.png')}}" alt="" width="25">
                            Logout
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('auth.index')}}" style="color: aliceblue;">Inicio</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.signin')}}" style="color: aliceblue;">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.signup')}}" style="color: aliceblue;">Registrarse</a>
                    </li>

                    {% endif %}
                  </ul>
            </div>
      

        </div>
    
      </nav>

{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% block container %}
        {% endblock%}
    </div>
</div>    
{% endblock %}